name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - '.github/workflows/build.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/386, linux/amd64, linux/arm, linux/arm/v6, linux/arm64, windows/386, windows/amd64, windows/arm64
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/ros-grpc:latest"
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
